GET http://localhost:3000/url

####
GET http://localhost:3000/ciudades?q=A

####
GET http://localhost:3000/my

####
POST http://localhost:3000/my
Content-Type: application/json

{
    "name":"Epa pitufo"
}

####
GET http://localhost:3000/api/translation